version: '3'

services:
  attendance-web:
    image: node:16.13
    volumes:
      - ${APP_PATH}:/var/www/attendance-server
    working_dir: /var/www/attendance-server
    user: node
    ports:
      - 3031:3000
    environment:
      - MYSQL_USER_NAME=attendance
      - MYSQL_USER_PASSWORD=attendance
    command: npm run dev
  attendance-admin:
    image: node:16.13
    volumes:
      - ${APP_PATH}:/var/www/attendance-server
    working_dir: /var/www/attendance-server
    user: node
    ports:
      - 3032:3000
    environment:
      - MYSQL_USER_NAME=attendance
      - MYSQL_USER_PASSWORD=attendance
    command: npm run admin
  attendance-lp:
    image: node:16.13
    volumes:
      - ${APP_PATH}:/var/www/attendance-server
    working_dir: /var/www/attendance-server
    user: node
    ports:
      - 3033:3000
    environment:
      - MYSQL_USER_NAME=attendance
      - MYSQL_USER_PASSWORD=attendance
    command: npm run lp
  attendance-db:
    image: mysql:5.7
    volumes:
      - attendance-db_data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: attendance
      MYSQL_DATABASE: attendance
      MYSQL_USER: attendance
      MYSQL_PASSWORD: attendance
  attendance-redis:
    image: redis
    volumes:
      - attendance-redis_data:/data
    ports:
      - 6379:6379
  attendance-migrate:
    image: ruby:2.7.5
    volumes:
      - ${ENV_PATH}:/env
    working_dir: /env/migration
    # command: bundle install && ENV=local PASS=attendance sh ./migration.sh
    tty: true
  attendance-minio:
    image: minio/minio
    volumes:
      - attendance-minio_data:/data
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: attendance
      MINIO_ROOT_PASSWORD: attendance
    command: server --console-address ":9001" /data


volumes:
  attendance-db_data:
  attendance-redis_data:
  attendance-minio_data:
